version: '3'
name: Union-des-rolistes

services:
  bot_base:
    build: ./bot #utilise le dockerfile pour cree le container a utiliser
    container_name: bot_base
    restart: always #redemarre le container si il s'eteint
    environment:
      - DISCORD_TOKEN=----------------------------------------- #token pour comm avec discord
      - BOT_PREFIX=$ #prefix pour les commandes
      #- BOT_EXTEND=coucou, coucou2 #extensions a charger
    volumes:
      - ./Bot/extends/base:/app/extends/base #dossier ou est l'extension de la base
  api:
    build: ./api #utilise le dockerfile pour cree le container a utiliser
    container_name: api_base
    ports:
      - "3000:80"
    restart: always #redemarre le container si il s'eteint
    environment:
      #reuse les variables d'environnement du container bot_base
      - DISCORD_TOKEN=-------------------------------------------
      - PYTHONUNBUFFERED=1 #get print of python
  php:
    image: php:8-apache
    # environment:
    #   - APACHE_HTTP_PORT_NUMBER=80
    # volumes:
    #   - ./apache/default-httpd.conf:/etc/apache2/apache2.conf:ro # si besoin de modifier le fichier de conf apache (normalement pas besoin)
    ports:
      - "80:80"
    restart: always
    depends_on:
      - bot_base
