version: '3'
name: uniondesroliste

services:
  bot_base:
    build: . #utilise le dockerfile pour cree le container a utiliser
    container_name: bot_base
    restart: always #redemarre le container si il s'eteint
    environment:
      - DISCORD_TOKEN=---------------------------------------- #token pour comm avec discord
      - BOT_PREFIX=$ #prefix pour les commandes
      #- BOT_EXTEND=coucou, coucou2 #extensions a charger
    volumes:
      - ./Bot/extends/base:/app/extends/base #dossier ou est l'extension de la base
  php:
    image: php:8-apache
    # environment:
    #   - APACHE_HTTP_PORT_NUMBER=80
    # volumes:
    #   - ./apache/default-httpd.conf:/etc/apache2/apache2.conf:ro # si besoin de modifier le fichier de conf apache (normalement pas besoin)
    ports:
      - "80:80"
    restart: always
    depends_on:
      - bot_base
